# Magnet.toml for basic workspace example
# This file is used by the magnet CLI tool to manage workspace dependencies

[project]
name = "basic-example"
version = "0.1.0"
description = "Example project demonstrating basic magnet features"
authors = ["Example User <user@example.com>"]

[workspace]
members = ["crates/*"]
exclude = []
resolver = "2"

# Define workspace dependencies that are shared across crates
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
chrono = "0.4"
env_logger = "0.10"

# Auto-detect crates within the workspace for path-based dependencies
core-crate = { auto = true }
utils-crate = { auto = true }
app-crate = { auto = true }