use std::collections::BTreeSet;
use std::fmt::Write as _;

use fp_core::ast::{
    AstSerializer, BlockStmt, Expr, ExprKind, File, Item,
    ItemDefEnum, ItemDefFunction, ItemDefStruct, ItemImport, ItemKind, ItemDefConst,
    Ty, TypeInt, TypePrimitive, StructuralField,
    EnumTypeVariant, FunctionParam, FormatTemplatePart,
    Value, ExprInvokeTarget,
    StmtLet, BExpr, Pattern, PatternKind,
};
use fp_core::ops::{BinOpKind, UnOpKind};
use fp_core::intrinsics::calls::{CallKind, KnownPackage, OpKind};
use fp_core::package::{PackageItem, PackageSource};
use eyre::{bail, Result};

// ── Emitter context ──────────────────────────────────────────────────────────

struct KotlinEmitter {
    code: String,
    indent: usize,
}

impl KotlinEmitter {
    fn new() -> Self { Self { code: String::new(), indent: 0 } }

    fn push_line(&mut self, line: &str) {
        for _ in 0..self.indent { self.code.push_str("    "); }
        self.code.push_str(line);
        self.code.push('\n');
    }

    fn push_str(&mut self, s: &str) { self.code.push_str(s); }
}

// ── Serializer entry ─────────────────────────────────────────────────────────

pub struct KotlinSerializer;

impl AstSerializer for KotlinSerializer {
    fn serialize_file(&self, file: &File) -> fp_core::error::Result<String> {
        let mut emitter = KotlinEmitter::new();
        emit_file(file, &mut emitter)?;
        let mut out = String::from("// Generated by FerroPhase — Kotlin target\n\n");
        out.push_str(&emitter.code);
        Ok(out)
    }
}

impl KotlinSerializer {
    /// Serialize a package into per-module Kotlin files with Gradle manifest.
    /// Returns `Vec<(relative_path, code)>` — source files + build files.
    pub fn serialize_package(&self, source: &PackageSource) -> Result<Vec<(String, String)>> {
        use std::collections::BTreeMap;
        let mut modules: BTreeMap<String, Vec<Item>> = BTreeMap::new();
        for pkg_item in &source.items {
            let key = pkg_item.path.segments.join("/");
            modules.entry(key).or_default().push(pkg_item.item.clone());
        }

        let pkg_name = &source.name;
        let mut files = Vec::new();

        // Collect cross-package dependencies from imports
        let deps = collect_workspace_deps(&source.items);

        // Gradle manifest
        files.push(("settings.gradle.kts".into(), settings_gradle(pkg_name)));
        files.push(("build.gradle.kts".into(), build_gradle(pkg_name, &deps)));

        // Source files under src/main/kotlin/
        for (mod_path, items) in modules {
            let file = File {
                path: std::path::PathBuf::from(&mod_path),
                attrs: Vec::new(),
                collected_items: Vec::new(),
                items,
            };
            let code = self.serialize_file(&file)
                .map_err(|e| eyre::eyre!("serialize {}: {}", mod_path, e))?;
            let out_path = format!("src/main/kotlin/{}.kt", mod_path);
            files.push((out_path, code));
        }
        Ok(files)
    }
}

fn settings_gradle(name: &str) -> String {
    format!("rootProject.name = \"{}\"\n", name.replace('-', "_"))
}

fn build_gradle(name: &str, deps: &[String]) -> String {
    let group = format!("com.{}", name.replace('-', "."));
    let dep_lines: String = deps.iter()
        .map(|d| format!("    implementation(project(\":{}\"))\n", d.replace('-', "_")))
        .collect();
    format!(
        "plugins {{\n    kotlin(\"jvm\") version \"2.1.0\"\n}}\n\n\
         group = \"{}\"\n\
         version = \"0.1.0\"\n\n\
         repositories {{\n    mavenCentral()\n}}\n\n\
         dependencies {{\n    testImplementation(kotlin(\"test\"))\n{}}}\n\n\
         kotlin {{\n    jvmToolchain(21)\n}}\n",
        group, dep_lines,
    )
}

fn collect_workspace_deps(items: &[PackageItem]) -> Vec<String> {
    use std::collections::BTreeSet;
    let mut deps = BTreeSet::new();
    for pkg_item in items {
        collect_deps_from_item(&pkg_item.item, &mut deps);
    }
    // Only return deps that reference known workspace packages (multi-segment paths
    // that start with a workspace package name like skln_core, skln_git)
    let known_workspace: &[&str] = &["skln_core", "skln_git"];
    deps.into_iter()
        .filter(|d| known_workspace.contains(&d.as_str()))
        .collect()
}

fn collect_deps_from_item(item: &Item, deps: &mut BTreeSet<String>) {
    use fp_core::ast::ItemKind;
    match item.kind() {
        ItemKind::Import(imp) => {
            let path = flatten_import_tree(&imp.tree);
            // Skip std, serde, winnow, relative imports, java
            if !path.starts_with("std.") && !path.starts_with("serde") 
                && !path.starts_with("winnow") && !path.starts_with('.')
                && !path.is_empty()
                && !path.starts_with("java")
            {
                let pkg = path.split('.').next().unwrap_or(&path);
                deps.insert(pkg.to_string());
            }
        }
        ItemKind::Module(m) => {
            for child in &m.items { collect_deps_from_item(child, deps); }
        }
        ItemKind::DefFunction(f) => {
            for stmt in &f.body.stmts { collect_deps_from_stmt(stmt, deps); }
        }
        _ => {}
    }
}

fn collect_deps_from_stmt(stmt: &BlockStmt, deps: &mut BTreeSet<String>) {
    match stmt {
        BlockStmt::Item(item) => collect_deps_from_item(item, deps),
        _ => {}
    }
}

fn emit_file(file: &File, e: &mut KotlinEmitter) -> Result<()> {
    let mut imports = Vec::new();
    let mut non_imports = Vec::new();
    for item in &file.items {
        if let ItemKind::Import(imp) = item.kind() { imports.push(imp.clone()); }
        else { non_imports.push(item); }
    }
    for imp in &imports { emit_import(imp, e)?; }
    if !imports.is_empty() { e.push_line(""); }
    for item in non_imports { emit_item(item, e)?; }
    Ok(())
}

// ── Items ────────────────────────────────────────────────────────────────────

fn emit_item(item: &Item, e: &mut KotlinEmitter) -> Result<()> {
    match item.kind() {
        ItemKind::DefStruct(s) => emit_struct(s, e),
        ItemKind::DefEnum(en) => emit_enum(en, e),
        ItemKind::DefFunction(f) => emit_function(f, e),
        ItemKind::Module(m) => {
            for child in &m.items { emit_item(child, e)?; }
            Ok(())
        }
        ItemKind::Import(imp) => emit_import(imp, e),
        ItemKind::DefConst(c) => {
            let name = c.name.name.as_str();
            let val = render_expr(&c.value, e)?;
            e.push_line(&format!("val {} = {}", name, val));
            Ok(())
        }
        ItemKind::DefTrait(_) | ItemKind::Impl(_) | ItemKind::Macro(_) | ItemKind::DefStructural(_) => Ok(()),
        ItemKind::Expr(expr) => {
            if let ExprKind::Block(block) = expr.kind() {
                for stmt in &block.stmts { emit_stmt(stmt, e, false)?; }
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ── Struct ───────────────────────────────────────────────────────────────────

fn emit_struct(s: &ItemDefStruct, e: &mut KotlinEmitter) -> Result<()> {
    let name = s.name.name.as_str();
    let fields = &s.value.fields;
    e.push_line(&format!("data class {}(", name));
    for (i, field) in fields.iter().enumerate() {
        let comma = if i < fields.len() - 1 { "," } else { "" };
        let kt = kotlin_type_from_ty(&field.value, e);
        e.push_line(&format!("    val {}: {}{}", field.name.name, kt, comma));
    }
    e.push_line(")\n");
    Ok(())
}

// ── Enum ─────────────────────────────────────────────────────────────────────

fn emit_enum(en: &ItemDefEnum, e: &mut KotlinEmitter) -> Result<()> {
    let name = en.name.name.as_str();
    let variants = &en.value.variants;
    e.push_line(&format!("enum class {} {{", name));
    for (i, variant) in variants.iter().enumerate() {
        let comma = if i < variants.len() - 1 { "," } else { "" };
        e.push_line(&format!("    {}{}", variant.name.name.to_uppercase(), comma));
    }
    e.push_line("}\n");
    Ok(())
}

// ── Function ─────────────────────────────────────────────────────────────────

fn emit_function(f: &ItemDefFunction, e: &mut KotlinEmitter) -> Result<()> {
    let name = f.name.name.as_str();
    let params = f.sig.params.iter()
        .map(|p| format!("{}: {}", p.name.name, kotlin_type_from_ty(&p.ty, e)))
        .collect::<Vec<_>>().join(", ");
    let ret = f.sig.ret_ty.as_ref()
        .map(|ty| format!(": {}", kotlin_type_from_ty(ty, e)))
        .unwrap_or_else(|| ": Unit".to_string());

    e.push_line(&format!("fun {}({}){} {{", name, params, ret));
    e.indent += 1;
    for stmt in &f.body.stmts { emit_stmt(stmt, e, false)?; }
    e.indent -= 1;
    e.push_line("}\n");
    Ok(())
}

// ── Import ───────────────────────────────────────────────────────────────────

fn emit_import(imp: &ItemImport, e: &mut KotlinEmitter) -> Result<()> {
    let path = flatten_import_tree(&imp.tree);
    if path.is_empty() { return Ok(()); }

    // Handle multi-name group imports: Rust `use foo::{A, B, C}` → `import foo.*`
    let effective = if path.contains(",") {
        let first = path.split(",").next().unwrap_or(&path);
        // Drop the last segment (the specific name) to get the parent module
        let parent = first.rsplitn(2, ".").nth(1).unwrap_or(first);
        if parent.is_empty() { ".*".to_string() } else { format!("{}.*", parent) }
    } else {
        path.clone()
    };

    let pkg = known_package(&effective);
    let kt = kt_import_for(pkg, &effective);
    if let Some(import) = kt {
        e.push_line(&format!("import {}", import));
    }
    Ok(())
}

fn known_package(path: &str) -> KnownPackage {
    use fp_core::intrinsics::calls::KnownPackage::*;
    match path {
        p if p.starts_with("std.collections") => StdCollections,
        p if p.starts_with("std.path") => StdPath,
        p if p.starts_with("std.process") => StdProcess,
        p if p.starts_with("std.sync") => StdSync,
        p if p.starts_with("std.fs") => StdFs,
        p if p.starts_with("std.io") => StdIo,
        p if p.starts_with("std.str") => StdStr,
        p if p.starts_with("std.option") => StdOption,
        p if p.starts_with("serde") => Serde,
        p if p.starts_with("winnow") => Winnow,
        _ => Other,
    }
}

fn kt_import_for(pkg: KnownPackage, path: &str) -> Option<String> {
    use fp_core::intrinsics::calls::KnownPackage::*;
    match pkg {
        // Built-in — skip
        StdCollections | StdSync | StdStr | StdOption | Serde | Winnow => None,
        // Mapped
        StdPath => Some("java.nio.file.Path".into()),
        StdProcess => Some("java.lang.ProcessBuilder".into()),
        StdFs => Some("java.io.File".into()),
        StdIo => Some("java.io.*".into()),
        // Local package — preserve as-is
        Other => Some(path.to_string()),
    }
}

fn flatten_import_tree(tree: &fp_core::ast::ItemImportTree) -> String {
    use fp_core::ast::ItemImportTree::*;
    match tree {
        Path(p) => p.segments.iter().map(|s| flatten_import_tree(s)).collect::<Vec<_>>().join("."),
        Ident(id) => id.name.clone(),
        Rename(r) => format!("{} as {}", r.from.name, r.to.name),
        Glob => "*".to_string(),
        Group(g) => g.items.iter().map(|i| flatten_import_tree(i)).collect::<Vec<_>>().join(", "),
        _ => String::new(),
    }
}

// ── Statements ───────────────────────────────────────────────────────────────

fn emit_stmt(stmt: &BlockStmt, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    match stmt {
        BlockStmt::Let(l) => {
            let var_name = ident_from_pattern(&l.pat);
            if var_name == "_" {
                if let Some(init) = &l.init {
                    let val = render_expr(init, e)?;
                    e.push_line(&val);
                }
            } else if let Some(init) = &l.init {
                let val = render_expr(init, e)?;
                e.push_line(&format!("val {} = {}", var_name, val));
            } else {
                e.push_line(&format!("val {} = null", var_name));
            }
        }
        BlockStmt::Expr(se) => emit_stmt_expr(&se.expr, e, is_tail)?,
        BlockStmt::Item(item) => return emit_item(item, e),
        BlockStmt::Noop => {}
        _ => {}
    }
    Ok(())
}

fn emit_stmt_expr(expr: &Expr, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    match expr.kind() {
        ExprKind::Block(block) => {
            e.push_line("{");
            e.indent += 1;
            for s in &block.stmts { emit_stmt(s, e, false)?; }
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::If(if_expr) => emit_if_stmt(if_expr, e, is_tail)?,
        ExprKind::While(wh) => {
            let cond = render_expr(&wh.cond, e)?;
            e.push_line(&format!("while ({}) {{", cond));
            e.indent += 1;
            emit_box_body(&wh.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::Loop(lp) => {
            e.push_line("while (true) {");
            e.indent += 1;
            emit_box_body(&lp.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::For(fr) => {
            let iter_expr = render_expr(&fr.iter, e)?;
            let var = ident_from_pattern(&fr.pat);
            e.push_line(&format!("for ({} in {}) {{", var, iter_expr));
            e.indent += 1;
            emit_box_body(&fr.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::Return(ret) => {
            if let Some(val) = &ret.value {
                let v = render_expr(val, e)?;
                e.push_line(&format!("return {}", v));
            } else { e.push_line("return"); }
        }
        ExprKind::Break(_) => { e.push_line("break"); }
        ExprKind::Continue(_) => { e.push_line("continue"); }
        _ => {
            let rendered = render_expr(expr, e)?;
            if is_tail { e.push_line(&format!("return {}", rendered)); }
            else { e.push_line(&rendered); }
        }
    }
    Ok(())
}

fn emit_if_stmt(if_expr: &fp_core::ast::ExprIf, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    let cond = render_expr(&if_expr.cond, e)?;
    e.push_line(&format!("if ({}) {{", cond));
    e.indent += 1;
    emit_box_body(&if_expr.then, e)?;
    e.indent -= 1;
    if let Some(elze) = &if_expr.elze {
        e.push_line("} else {");
        e.indent += 1;
        emit_box_body(elze, e)?;
        e.indent -= 1;
    }
    e.push_line("}");
    Ok(())
}

fn emit_box_body(body: &BExpr, e: &mut KotlinEmitter) -> Result<()> {
    if let ExprKind::Block(block) = body.kind() {
        for s in &block.stmts { emit_stmt(s, e, false)?; }
    } else {
        let val = render_expr(body, e)?;
        e.push_line(&val);
    }
    Ok(())
}

fn ident_from_pattern(pat: &Pattern) -> String {
    match &pat.kind {
        PatternKind::Ident(id) => id.ident.name.clone(),
        PatternKind::Tuple(t) => {
            let names: Vec<String> = t.patterns.iter().map(|p| ident_from_pattern(p)).collect();
            format!("({})", names.join(", "))
        }
        _ => "_".to_string(),
    }
}

// ── Expressions ──────────────────────────────────────────────────────────────

fn render_expr(expr: &Expr, e: &mut KotlinEmitter) -> Result<String> {
    match expr.kind() {
        ExprKind::Value(val) => Ok(render_value(val)),
        ExprKind::Name(name) => Ok(name.to_string().replace("::", ".")),
        ExprKind::Id(id) => Ok(id.to_string()),

        ExprKind::Invoke(inv) => {
            match &inv.target {
                ExprInvokeTarget::Method(sel) => {
                    let obj = render_expr(&sel.obj, e)?;
                    let args: Vec<String> = inv.args.iter()
                        .map(|a| render_expr(a, e))
                        .collect::<Result<Vec<_>>>()?;
                    Ok(format!("{}.{}({})", obj, sel.field.name, args.join(", ")))
                }
                _ => {
                    let func = map_kt_method(&invoke_name(&inv.target));
                    let args: Vec<String> = inv.args.iter()
                        .map(|a| render_expr(a, e))
                        .collect::<Result<Vec<_>>>()?;
                    Ok(format!("{}({})", func, args.join(", ")))
                }
            }
        }

        ExprKind::Select(sel) => {
            Ok(format!("{}.{}", render_expr(&sel.obj, e)?, sel.field.name))
        }

        ExprKind::Index(idx) => {
            Ok(format!("{}[{}]", render_expr(&idx.obj, e)?, render_expr(&idx.index, e)?))
        }

        ExprKind::BinOp(bin) => {
            Ok(format!("({} {} {})", render_expr(&bin.lhs, e)?, kotlin_bin_op(&bin.kind), render_expr(&bin.rhs, e)?))
        }

        ExprKind::UnOp(un) => {
            Ok(format!("{}({})", kotlin_un_op(&un.op), render_expr(&un.val, e)?))
        }

        ExprKind::If(if_expr) => {
            let cond = render_expr(&if_expr.cond, e)?;
            let then_val = render_expr_single(&if_expr.then, e)?;
            if let Some(elze) = &if_expr.elze {
                Ok(format!("if ({}) {} else {}", cond, then_val, render_expr_single(elze, e)?))
            } else {
                Ok(format!("if ({}) {}", cond, then_val))
            }
        }

        ExprKind::Match(mt) => {
            let scrutinee = mt.scrutinee.as_ref()
                .map(|s| render_expr(s, e)).transpose()?
                .unwrap_or_else(|| "null".to_string());

            // Single non-wildcard arm → if (x) { body }
            if mt.cases.len() == 1 && !matches!(mt.cases[0].pat.as_ref().map(|p| &p.kind), Some(PatternKind::Wildcard(_))) {
                let case = &mt.cases[0];
                let pat_var = match_case_binding(&case.pat);
                let body = render_expr(&case.body, e)?;
                if let Some(var) = pat_var {
                    Ok(format!("if ({0} != null) {{ val {1} = {0}!!; {2} }}", scrutinee, var, body))
                } else {
                    Ok(format!("if ({}) {{ {} }}", scrutinee, body))
                }
            } else {
                let mut buf = format!("when ({}) {{\n", scrutinee);
                for case in &mt.cases {
                    let pat = render_match_pat(&case.pat);
                    let body = render_expr(&case.body, e)?;
                    let _ = writeln!(buf, "        {} -> {}", pat, body);
                }
                for _ in 0..e.indent { buf.push_str("    "); }
                buf.push('}');
                Ok(buf)
            }
        }

        ExprKind::Block(block) => {
            let mut buf = String::new();
            for stmt in &block.stmts {
                let saved = std::mem::take(&mut e.code);
                e.indent += 1;
                emit_stmt(stmt, e, false)?;
                let stmt_text = std::mem::replace(&mut e.code, saved);
                buf.push_str(&stmt_text);
                e.indent -= 1;
            }
            Ok(buf)
        }

        ExprKind::Assign(assign) => {
            Ok(format!("{} = {}", render_expr(&assign.target, e)?, render_expr(&assign.value, e)?))
        }

        ExprKind::Struct(st) => {
            let name = render_expr(&st.name, e)?;
            let fields: Vec<String> = st.fields.iter().map(|f| {
                let val = match &f.value { Some(v) => render_expr(v, e)?, None => "null".to_string() };
                Ok(format!("{} = {}", f.name.name, val))
            }).collect::<Result<Vec<_>>>()?;
            Ok(format!("{}({})", name, fields.join(", ")))
        }

        ExprKind::Array(arr) => {
            let items: Vec<String> = arr.values.iter().map(|v| render_expr(v, e)).collect::<Result<Vec<_>>>()?;
            Ok(format!("listOf({})", items.join(", ")))
        }

        ExprKind::Tuple(tup) => {
            let items: Vec<String> = tup.values.iter().map(|v| render_expr(v, e)).collect::<Result<Vec<_>>>()?;
            Ok(format!("Pair({})", items.join(", ")))
        }

        ExprKind::Reference(r) => render_expr(&r.referee, e),
        ExprKind::Dereference(d) => render_expr(&d.referee, e),
        ExprKind::Cast(c) => render_expr(&c.expr, e),
        ExprKind::Paren(p) => Ok(format!("({})", render_expr(&p.expr, e)?)),

        ExprKind::Closure(cl) => {
            let params: Vec<String> = cl.params.iter().map(|p| {
                let n = ident_from_pattern(p);
                if n == "_" { "it".to_string() } else { n }
            }).collect();
            Ok(format!("{{ {} -> {} }}", params.join(", "), render_expr_single(&cl.body, e)?))
        }

        ExprKind::Let(l) => {
            Ok(format!("val {} = {}", ident_from_pattern(&l.pat), render_expr(&l.expr, e)?))
        }

        ExprKind::Return(ret) => {
            if let Some(val) = &ret.value {
                Ok(format!("return {}", render_expr(val, e)?))
            } else { Ok("return".to_string()) }
        }

        ExprKind::IntrinsicCall(ic) => {
            use fp_core::intrinsics::calls::OpKind;
            // Render all args first to avoid borrow conflicts
            let args: Vec<String> = ic.args.iter()
                .map(|a| render_expr(a, e))
                .collect::<Result<Vec<_>>>()?;

            match &ic.kind {
                CallKind::Op(OpKind::MapOr) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    let default = args.get(1).cloned().unwrap_or_default();
                    Ok(format!("{} ?: {}", receiver, default))
                }
                CallKind::Op(OpKind::Collect) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    Ok(format!("{}.toList()", receiver))
                }
                CallKind::Op(OpKind::Find) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    let pred = args.get(1).cloned();
                    if let Some(p) = pred {
                        Ok(format!("{}.firstOrNull {{ {} }}", receiver, p))
                    } else {
                        Ok(format!("{}.firstOrNull()", receiver))
                    }
                }
                CallKind::Op(OpKind::UnwrapOr) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    let default = args.get(1).cloned().unwrap_or_default();
                    Ok(format!("{} ?: {}", receiver, default))
                }
                CallKind::Op(OpKind::ToString) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    Ok(format!("{}.toString()", receiver))
                }
                CallKind::Op(OpKind::AndThen) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    Ok(format!("{}.let {{ it }}", receiver))
                }
                CallKind::Op(OpKind::OptionUnwrap) => {
                    let receiver = args.first().cloned().unwrap_or_default();
                    Ok(format!("{}!!", receiver))
                }
                _ => {
                    let name = intrinsic_name(&ic.kind);
                    Ok(format!("{}({})", name, args.join(", ")))
                }
            }
        }

        ExprKind::Range(r) => {
            let start = r.start.as_ref().map(|s| render_expr(s, e)).transpose()?;
            let end = r.end.as_ref().map(|s| render_expr(s, e)).transpose()?;
            Ok(match (start, end) {
                (Some(s), Some(en)) => format!("{}..{}", s, en),
                (Some(s), None) => format!("{}..", s),
                (None, Some(en)) => format!("..{}", en),
                (None, None) => "..".to_string(),
            })
        }

        ExprKind::FormatString(fs) => {
            let parts = fs.parts.iter().map(|p| match p {
                FormatTemplatePart::Literal(lit) => Ok(lit.clone()),
                FormatTemplatePart::Placeholder(_ph) => {
                    let rendered = "arg".to_string();
                    Ok(format!("${{{}}}", rendered))
                }
            }).collect::<Result<Vec<_>>>()?;
            Ok(format!("\"{}\"", parts.join("")))
        }

        ExprKind::Break(_) => Ok("break".to_string()),
        ExprKind::Continue(_) => Ok("continue".to_string()),
        _ => Ok(String::new()),
    }
}

fn render_expr_single(body: &BExpr, e: &mut KotlinEmitter) -> Result<String> {
    if let ExprKind::Block(block) = body.kind() {
        let mut parts = Vec::new();
        for stmt in &block.stmts {
            if let BlockStmt::Expr(se) = stmt { parts.push(render_expr(&se.expr, e)?); }
        }
        Ok(parts.join(" "))
    } else { render_expr(body, e) }
}

fn render_invoke_target(target: &ExprInvokeTarget, e: &mut KotlinEmitter) -> Result<String> {
    match target {
        ExprInvokeTarget::Function(name) => Ok(name.to_string().replace("::", ".")),
        ExprInvokeTarget::Method(sel) => Ok(format!("{}.{}", render_expr(&sel.obj, e)?, sel.field.name)),
        ExprInvokeTarget::Expr(bexpr) => render_expr(bexpr, e),
        _ => Ok("call".to_string()),
    }
}

fn invoke_name(target: &ExprInvokeTarget) -> String {
    match target {
        ExprInvokeTarget::Function(name) => name.to_string(),
        ExprInvokeTarget::Method(sel) => {
            format!(".{}", sel.field.name)
        }
        _ => String::new(),
    }
}

fn map_kt_method(name: &str) -> String {
    match name {
        "Vec::new" | "Vec" => "mutableListOf".into(),
        "HashSet::new" => "mutableSetOf".into(),
        "HashMap::new" => "mutableMapOf".into(),
        "unwrap" | "expect" => "!!".into(),
        "is_empty" => "isEmpty()".into(),
        "push" => "add".into(),
        "pop" => "removeLast()".into(),
        "remove" => "removeAt".into(),
        "insert" => "add".into(),
        "len" => "size".into(),
        "lines" => "lines()".into(),
        "split" => "split".into(),
        "contains" => "contains".into(),
        "replace" => "replace".into(),
        "trim" => "trim()".into(),
        "to_uppercase" => "uppercase()".into(),
        "to_lowercase" => "lowercase()".into(),
        "starts_with" => "startsWith".into(),
        "ends_with" => "endsWith".into(),
        "strip_prefix" => "removePrefix".into(),
        "strip_suffix" => "removeSuffix".into(),
        "parse" => "toLong()".into(),
        "rfind" => "lastIndexOf".into(),
        "clone" => "copy()".into(),
        _ => name.replace("::", "."),
    }
}

fn render_match_pat(pat: &Option<fp_core::ast::BPattern>) -> String {
    match pat {
        Some(p) => match &p.kind {
            PatternKind::Ident(id) => id.ident.name.clone(),
            PatternKind::Wildcard(_) => "else".to_string(),
            PatternKind::Struct(s) => s.fields.iter()
                .map(|f| f.name.name.clone())
                .collect::<Vec<_>>().join(", "),
            PatternKind::Tuple(t) => t.patterns.iter()
                .map(|p| render_match_pat(&Some(Box::new(p.clone()))))
                .collect::<Vec<_>>().join(", "),
            PatternKind::TupleStruct(ts) => {
                let inner = ts.patterns.iter()
                    .map(|p| render_match_pat(&Some(Box::new(p.clone()))))
                    .collect::<Vec<_>>().join(", ");
                format!("{}({})", ts.name.to_string(), inner)
            }
            _ => "else".to_string(),
        },
        None => "else".to_string(),
    }
}

/// Extract a binding variable name from the first struct field of a match arm.
fn match_case_binding(pat: &Option<fp_core::ast::BPattern>) -> Option<String> {
    match pat {
        Some(p) => match &p.kind {
            PatternKind::Ident(id) => Some(id.ident.name.clone()),
            PatternKind::Struct(s) => s.fields.first().map(|f| f.name.name.clone()),
            _ => None,
        },
        None => None,
    }
}

// ── Value ────────────────────────────────────────────────────────────────────

fn render_value(val: &Value) -> String {
    match val {
        Value::Bool(v) => v.value.to_string(),
        Value::Int(v) => v.value.to_string(),
        Value::UInt(v) => v.value.to_string(),
        Value::BigInt(v) => v.value.to_string(),
        Value::Decimal(v) => v.value.to_string(),
        Value::BigDecimal(v) => v.value.to_string(),
        Value::Char(v) => format!("'{}'", v.value),
        Value::String(v) => format!("\"{}\"", v.value.escape_default()),
        Value::Unit(_) | Value::Null(_) | Value::None(_) => "null".to_string(),
        Value::Some(v) => render_value(&v.value),
        Value::Option(v) => v.value.as_ref().map(|i| render_value(i)).unwrap_or_else(|| "null".to_string()),
        Value::List(l) => {
            let items: Vec<String> = l.values.iter().map(|v| render_value(v)).collect();
            format!("listOf({})", items.join(", "))
        }
        Value::Map(m) => {
            let entries: Vec<String> = m.entries.iter()
                .map(|e| format!("{} to {}", render_value(&e.key), render_value(&e.value)))
                .collect();
            format!("mapOf({})", entries.join(", "))
        }
        Value::Tuple(t) => {
            let items: Vec<String> = t.values.iter().map(|v| render_value(v)).collect();
            format!("Pair({})", items.join(", "))
        }
        _ => "null".to_string(),
    }
}

// ── Operators ────────────────────────────────────────────────────────────────

fn kotlin_bin_op(kind: &BinOpKind) -> &str {
    match kind {
        BinOpKind::Add => "+", BinOpKind::Sub => "-", BinOpKind::Mul => "*", BinOpKind::Div => "/",
        BinOpKind::Mod => "%", BinOpKind::And | BinOpKind::BitAnd => "&&",
        BinOpKind::Or | BinOpKind::BitOr => "||", BinOpKind::Eq => "==", BinOpKind::Ne => "!=",
        BinOpKind::Lt => "<", BinOpKind::Gt => ">", BinOpKind::Le => "<=", BinOpKind::Ge => ">=",
        BinOpKind::Shl => "shl", BinOpKind::Shr => "shr", BinOpKind::BitXor => "xor",
        _ => "?",
    }
}

fn kotlin_un_op(kind: &UnOpKind) -> &str {
    match kind { UnOpKind::Not => "!", UnOpKind::Neg => "-", UnOpKind::Deref => "*", _ => "?" }
}

fn intrinsic_name(kind: &fp_core::intrinsics::calls::CallKind) -> String {
    use fp_core::intrinsics::calls::OpKind;
    use fp_core::intrinsics::calls::IntrinsicKind;
    match kind {
        fp_core::intrinsics::calls::CallKind::Op(op) => match op {
            OpKind::Print => "print".into(),
            OpKind::Println => "println".into(),
            OpKind::Format => "String.format".into(),
            _ => format!("op_{:?}", op).to_lowercase(),
        },
        fp_core::intrinsics::calls::CallKind::Intrinsic(i) => match i {
            IntrinsicKind::Len => "count()".into(),
            IntrinsicKind::Panic => "error".into(),
            _ => format!("intr_{:?}", i).to_lowercase(),
        },
    }
}

// ── Type mapping ─────────────────────────────────────────────────────────────

fn kotlin_type_from_ty(ty: &Ty, _e: &KotlinEmitter) -> String {
    match ty {
        Ty::Primitive(prim) => match prim {
            TypePrimitive::Bool => "Boolean".into(),
            TypePrimitive::Char => "Char".into(),
            TypePrimitive::String => "String".into(),
            TypePrimitive::Int(int_ty) => match int_ty {
                TypeInt::I8 => "Byte".into(), TypeInt::I16 => "Short".into(),
                TypeInt::I32 => "Int".into(), TypeInt::I64 => "Long".into(),
                TypeInt::U8 => "UByte".into(), TypeInt::U16 => "UShort".into(),
                TypeInt::U32 => "UInt".into(), TypeInt::U64 => "ULong".into(),
                _ => "Int".into(),
            },
            TypePrimitive::Decimal(d) => match d {
                fp_core::ast::DecimalType::F32 => "Float".into(),
                fp_core::ast::DecimalType::F64 => "Double".into(),
                _ => "Double".into(),
            },
            TypePrimitive::List => "List<Any>".into(),
        },
        Ty::Vec(v) => format!("List<{}>", kotlin_type_from_ty(&v.ty, _e)),
        Ty::Struct(s) => s.name.name.clone(),
        Ty::Enum(en) => en.name.name.clone(),
        Ty::Reference(r) => kotlin_type_from_ty(&r.ty, _e),
        Ty::Expr(expr) => map_name_to_kt(&expr_to_name(expr)),
        Ty::Unit(_) => "Unit".into(),
        Ty::Slice(sl) => format!("List<{}>", kotlin_type_from_ty(&sl.elem, _e)),
        Ty::Any(_) | Ty::Unknown(_) => "Any".into(),
        Ty::Nothing(_) => "Nothing".into(),
        _ => "Any".into(),
    }
}

fn expr_to_name(expr: &Expr) -> String {
    match expr.kind() {
        ExprKind::Name(name) => name_to_string(name),
        ExprKind::Select(sel) => {
            format!("{}.{}", expr_to_name(&sel.obj), sel.field.name.as_str())
        }
        _ => format!("Any"),
    }
}

fn name_to_string(name: &fp_core::ast::Name) -> String {
    use fp_core::ast::Name::*;
    match name {
        Ident(id) => id.name.clone(),
        Path(p) => p.segments.iter().map(|s| s.name.as_str()).collect::<Vec<_>>().join("."),
        ParameterPath(pp) => {
            let base = pp.segments.iter()
                .map(|s| {
                    let name = s.ident.name.as_str();
                    if s.args.is_empty() { name.to_string() }
                    else {
                        let args = s.args.iter()
                            .map(|ty| kotlin_type_from_ty(ty, &KotlinEmitter::new()))
                            .collect::<Vec<_>>().join(", ");
                        format!("{}<{}>", name, args)
                    }
                })
                .collect::<Vec<_>>().join(".");
            base
        },
    }
}

fn map_name_to_kt(name: &str) -> String {
    if let Some(inner) = name.strip_prefix("Vec<").and_then(|s| s.strip_suffix(">")) {
        return format!("MutableList<{}>", map_name_to_kt(inner));
    }
    if let Some(inner) = name.strip_prefix("Option<").and_then(|s| s.strip_suffix(">")) {
        return format!("{}?", map_name_to_kt(inner));
    }
    if let Some(inner) = name.strip_prefix("Arc<").and_then(|s| s.strip_suffix(">")) {
        return map_name_to_kt(inner);
    }
    if let Some(inner) = name.strip_prefix("ModalResult<").and_then(|s| s.strip_suffix(">")) {
        return map_name_to_kt(inner);
    }
    if let Some(inner) = name.strip_prefix("Box<").and_then(|s| s.strip_suffix(">")) {
        return map_name_to_kt(inner);
    }
    match name {
        "str" | "String" => "String".into(),
        "char" => "Char".into(),
        "bool" => "Boolean".into(),
        "i8" => "Byte".into(), "i16" => "Short".into(),
        "i32" => "Int".into(), "i64" => "Long".into(),
        "u8" => "UByte".into(), "u16" => "UShort".into(),
        "u32" => "UInt".into(), "u64" => "ULong".into(),
        "f32" => "Float".into(), "f64" => "Double".into(),
        "usize" => "Long".into(), "isize" => "Long".into(),
        "PathBuf" | "Path" => "java.nio.file.Path".into(),
        "Arc" => "Any".into(),
        "ModalResult" => "Any".into(),
        "Box" => "Any".into(),
        _ => name.to_string(),
    }
}
