use std::fmt::Write as _;

use fp_core::ast::{
    AstSerializer, BlockStmt, Expr, ExprKind, File, Item,
    ItemDefEnum, ItemDefFunction, ItemDefStruct, ItemImport, ItemKind, ItemDefConst,
    Ty, TypeInt, TypePrimitive, StructuralField,
    EnumTypeVariant, FunctionParam, FormatTemplatePart,
    Value, ExprInvokeTarget,
    StmtLet, BExpr, Pattern, PatternKind,
};
use fp_core::ops::{BinOpKind, UnOpKind};
use eyre::{bail, Result};

// ── Emitter context ──────────────────────────────────────────────────────────

struct KotlinEmitter {
    code: String,
    indent: usize,
}

impl KotlinEmitter {
    fn new() -> Self { Self { code: String::new(), indent: 0 } }

    fn push_line(&mut self, line: &str) {
        for _ in 0..self.indent { self.code.push_str("    "); }
        self.code.push_str(line);
        self.code.push('\n');
    }

    fn push_str(&mut self, s: &str) { self.code.push_str(s); }
}

// ── Serializer entry ─────────────────────────────────────────────────────────

pub struct KotlinSerializer;

impl AstSerializer for KotlinSerializer {
    fn serialize_file(&self, file: &File) -> fp_core::error::Result<String> {
        let mut emitter = KotlinEmitter::new();
        emit_file(file, &mut emitter)?;
        let mut out = String::from("// Generated by FerroPhase — Kotlin target\n\n");
        out.push_str(&emitter.code);
        Ok(out)
    }
}

fn emit_file(file: &File, e: &mut KotlinEmitter) -> Result<()> {
    let mut imports = Vec::new();
    let mut non_imports = Vec::new();
    for item in &file.items {
        if let ItemKind::Import(imp) = item.kind() { imports.push(imp.clone()); }
        else { non_imports.push(item); }
    }
    for imp in &imports { emit_import(imp, e)?; }
    if !imports.is_empty() { e.push_line(""); }
    for item in non_imports { emit_item(item, e)?; }
    Ok(())
}

// ── Items ────────────────────────────────────────────────────────────────────

fn emit_item(item: &Item, e: &mut KotlinEmitter) -> Result<()> {
    match item.kind() {
        ItemKind::DefStruct(s) => emit_struct(s, e),
        ItemKind::DefEnum(en) => emit_enum(en, e),
        ItemKind::DefFunction(f) => emit_function(f, e),
        ItemKind::Module(m) => {
            for child in &m.items { emit_item(child, e)?; }
            Ok(())
        }
        ItemKind::Import(imp) => emit_import(imp, e),
        ItemKind::DefConst(c) => {
            let name = c.name.name.as_str();
            let val = render_expr(&c.value, e)?;
            e.push_line(&format!("val {} = {}", name, val));
            Ok(())
        }
        ItemKind::DefTrait(_) | ItemKind::Impl(_) | ItemKind::Macro(_) | ItemKind::DefStructural(_) => Ok(()),
        ItemKind::Expr(expr) => {
            if let ExprKind::Block(block) = expr.kind() {
                for stmt in &block.stmts { emit_stmt(stmt, e, false)?; }
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ── Struct ───────────────────────────────────────────────────────────────────

fn emit_struct(s: &ItemDefStruct, e: &mut KotlinEmitter) -> Result<()> {
    let name = s.name.name.as_str();
    let fields = &s.value.fields;
    e.push_line(&format!("data class {}(", name));
    for (i, field) in fields.iter().enumerate() {
        let comma = if i < fields.len() - 1 { "," } else { "" };
        let kt = kotlin_type_from_ty(&field.value, e);
        e.push_line(&format!("    val {}: {}{}", field.name.name, kt, comma));
    }
    e.push_line(")\n");
    Ok(())
}

// ── Enum ─────────────────────────────────────────────────────────────────────

fn emit_enum(en: &ItemDefEnum, e: &mut KotlinEmitter) -> Result<()> {
    let name = en.name.name.as_str();
    let variants = &en.value.variants;
    e.push_line(&format!("enum class {} {{", name));
    for (i, variant) in variants.iter().enumerate() {
        let comma = if i < variants.len() - 1 { "," } else { "" };
        e.push_line(&format!("    {}{}", variant.name.name.to_uppercase(), comma));
    }
    e.push_line("}\n");
    Ok(())
}

// ── Function ─────────────────────────────────────────────────────────────────

fn emit_function(f: &ItemDefFunction, e: &mut KotlinEmitter) -> Result<()> {
    let name = f.name.name.as_str();
    let params = f.sig.params.iter()
        .map(|p| format!("{}: {}", p.name.name, kotlin_type_from_ty(&p.ty, e)))
        .collect::<Vec<_>>().join(", ");
    let ret = f.sig.ret_ty.as_ref()
        .map(|ty| format!(": {}", kotlin_type_from_ty(ty, e)))
        .unwrap_or_default();

    e.push_line(&format!("fun {}({}){} {{", name, params, ret));
    e.indent += 1;
    for stmt in &f.body.stmts { emit_stmt(stmt, e, false)?; }
    e.indent -= 1;
    e.push_line("}\n");
    Ok(())
}

// ── Import ───────────────────────────────────────────────────────────────────

fn emit_import(imp: &ItemImport, e: &mut KotlinEmitter) -> Result<()> {
    let path = flatten_import_tree(&imp.tree);
    if !path.is_empty() { e.push_line(&format!("import {}", path)); }
    Ok(())
}

fn flatten_import_tree(tree: &fp_core::ast::ItemImportTree) -> String {
    use fp_core::ast::ItemImportTree::*;
    match tree {
        Path(p) => p.segments.iter().map(|s| flatten_import_tree(s)).collect::<Vec<_>>().join("."),
        Ident(id) => id.name.clone(),
        Rename(r) => format!("{} as {}", r.from.name, r.to.name),
        Glob => "*".to_string(),
        Group(g) => g.items.iter().map(|i| flatten_import_tree(i)).collect::<Vec<_>>().join(", "),
        _ => String::new(),
    }
}

// ── Statements ───────────────────────────────────────────────────────────────

fn emit_stmt(stmt: &BlockStmt, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    match stmt {
        BlockStmt::Let(l) => {
            let var_name = ident_from_pattern(&l.pat);
            if let Some(init) = &l.init {
                let val = render_expr(init, e)?;
                e.push_line(&format!("val {} = {}", var_name, val));
            } else {
                e.push_line(&format!("val {} = null", var_name));
            }
        }
        BlockStmt::Expr(se) => emit_stmt_expr(&se.expr, e, is_tail)?,
        BlockStmt::Item(item) => return emit_item(item, e),
        BlockStmt::Noop => {}
        _ => {}
    }
    Ok(())
}

fn emit_stmt_expr(expr: &Expr, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    match expr.kind() {
        ExprKind::Block(block) => {
            e.push_line("{");
            e.indent += 1;
            for s in &block.stmts { emit_stmt(s, e, false)?; }
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::If(if_expr) => emit_if_stmt(if_expr, e, is_tail)?,
        ExprKind::While(wh) => {
            let cond = render_expr(&wh.cond, e)?;
            e.push_line(&format!("while ({}) {{", cond));
            e.indent += 1;
            emit_box_body(&wh.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::Loop(lp) => {
            e.push_line("while (true) {");
            e.indent += 1;
            emit_box_body(&lp.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::For(fr) => {
            let iter_expr = render_expr(&fr.iter, e)?;
            let var = ident_from_pattern(&fr.pat);
            e.push_line(&format!("for ({} in {}) {{", var, iter_expr));
            e.indent += 1;
            emit_box_body(&fr.body, e)?;
            e.indent -= 1;
            e.push_line("}");
        }
        ExprKind::Return(ret) => {
            if let Some(val) = &ret.value {
                let v = render_expr(val, e)?;
                e.push_line(&format!("return {}", v));
            } else { e.push_line("return"); }
        }
        ExprKind::Break(_) => { e.push_line("break"); }
        ExprKind::Continue(_) => { e.push_line("continue"); }
        _ => {
            let rendered = render_expr(expr, e)?;
            if is_tail { e.push_line(&format!("return {}", rendered)); }
            else { e.push_line(&rendered); }
        }
    }
    Ok(())
}

fn emit_if_stmt(if_expr: &fp_core::ast::ExprIf, e: &mut KotlinEmitter, is_tail: bool) -> Result<()> {
    let cond = render_expr(&if_expr.cond, e)?;
    e.push_line(&format!("if ({}) {{", cond));
    e.indent += 1;
    emit_box_body(&if_expr.then, e)?;
    e.indent -= 1;
    if let Some(elze) = &if_expr.elze {
        e.push_line("} else {");
        e.indent += 1;
        emit_box_body(elze, e)?;
        e.indent -= 1;
    }
    e.push_line("}");
    Ok(())
}

fn emit_box_body(body: &BExpr, e: &mut KotlinEmitter) -> Result<()> {
    if let ExprKind::Block(block) = body.kind() {
        for s in &block.stmts { emit_stmt(s, e, false)?; }
    } else {
        let val = render_expr(body, e)?;
        e.push_line(&val);
    }
    Ok(())
}

fn ident_from_pattern(pat: &Pattern) -> String {
    match &pat.kind {
        PatternKind::Ident(id) => id.ident.name.clone(),
        _ => "_".to_string(),
    }
}

// ── Expressions ──────────────────────────────────────────────────────────────

fn render_expr(expr: &Expr, e: &mut KotlinEmitter) -> Result<String> {
    match expr.kind() {
        ExprKind::Value(val) => Ok(render_value(val)),
        ExprKind::Name(name) => Ok(name.to_string().replace("::", ".")),
        ExprKind::Id(id) => Ok(id.to_string()),

        ExprKind::Invoke(inv) => {
            let args: Vec<String> = inv.args.iter()
                .map(|a| render_expr(a, e))
                .collect::<Result<Vec<_>>>()?;
            Ok(format!("{}({})", render_invoke_target(&inv.target, e)?, args.join(", ")))
        }

        ExprKind::Select(sel) => {
            Ok(format!("{}.{}", render_expr(&sel.obj, e)?, sel.field.name))
        }

        ExprKind::Index(idx) => {
            Ok(format!("{}[{}]", render_expr(&idx.obj, e)?, render_expr(&idx.index, e)?))
        }

        ExprKind::BinOp(bin) => {
            Ok(format!("({} {} {})", render_expr(&bin.lhs, e)?, kotlin_bin_op(&bin.kind), render_expr(&bin.rhs, e)?))
        }

        ExprKind::UnOp(un) => {
            Ok(format!("{}({})", kotlin_un_op(&un.op), render_expr(&un.val, e)?))
        }

        ExprKind::If(if_expr) => {
            let cond = render_expr(&if_expr.cond, e)?;
            let then_val = render_expr_single(&if_expr.then, e)?;
            if let Some(elze) = &if_expr.elze {
                Ok(format!("if ({}) {} else {}", cond, then_val, render_expr_single(elze, e)?))
            } else {
                Ok(format!("if ({}) {}", cond, then_val))
            }
        }

        ExprKind::Match(mt) => {
            let scrutinee = mt.scrutinee.as_ref()
                .map(|s| render_expr(s, e)).transpose()?
                .unwrap_or_else(|| "null".to_string());
            let mut buf = format!("when ({}) {{\n", scrutinee);
            for case in &mt.cases {
                let pat = render_match_pat(&case.pat);
                let body = render_expr(&case.body, e)?;
                let _ = writeln!(buf, "        {} -> {}", pat, body);
            }
            for _ in 0..e.indent { buf.push_str("    "); }
            buf.push('}');
            Ok(buf)
        }

        ExprKind::Block(block) => {
            let mut buf = String::new();
            for stmt in &block.stmts {
                let saved = std::mem::take(&mut e.code);
                e.indent += 1;
                emit_stmt(stmt, e, false)?;
                let stmt_text = std::mem::replace(&mut e.code, saved);
                buf.push_str(&stmt_text);
                e.indent -= 1;
            }
            Ok(buf)
        }

        ExprKind::Assign(assign) => {
            Ok(format!("{} = {}", render_expr(&assign.target, e)?, render_expr(&assign.value, e)?))
        }

        ExprKind::Struct(st) => {
            let name = render_expr(&st.name, e)?;
            let fields: Vec<String> = st.fields.iter().map(|f| {
                let val = match &f.value { Some(v) => render_expr(v, e)?, None => "null".to_string() };
                Ok(format!("{} = {}", f.name.name, val))
            }).collect::<Result<Vec<_>>>()?;
            Ok(format!("{}({})", name, fields.join(", ")))
        }

        ExprKind::Array(arr) => {
            let items: Vec<String> = arr.values.iter().map(|v| render_expr(v, e)).collect::<Result<Vec<_>>>()?;
            Ok(format!("listOf({})", items.join(", ")))
        }

        ExprKind::Tuple(tup) => {
            let items: Vec<String> = tup.values.iter().map(|v| render_expr(v, e)).collect::<Result<Vec<_>>>()?;
            Ok(format!("Pair({})", items.join(", ")))
        }

        ExprKind::Reference(r) => render_expr(&r.referee, e),
        ExprKind::Dereference(d) => render_expr(&d.referee, e),
        ExprKind::Cast(c) => render_expr(&c.expr, e),
        ExprKind::Paren(p) => Ok(format!("({})", render_expr(&p.expr, e)?)),

        ExprKind::Closure(cl) => {
            let params: Vec<String> = cl.params.iter().map(|p| ident_from_pattern(p)).collect();
            Ok(format!("{{ {} -> {} }}", params.join(", "), render_expr_single(&cl.body, e)?))
        }

        ExprKind::Let(l) => {
            Ok(format!("val {} = {}", ident_from_pattern(&l.pat), render_expr(&l.expr, e)?))
        }

        ExprKind::Return(ret) => {
            if let Some(val) = &ret.value {
                Ok(format!("return {}", render_expr(val, e)?))
            } else { Ok("return".to_string()) }
        }

        ExprKind::IntrinsicCall(ic) => {
            let args: Vec<String> = ic.args.iter()
                .map(|a| render_expr(a, e)).collect::<Result<Vec<_>>>()?;
            let name = intrinsic_name(&ic.kind);
            Ok(format!("{}({})", name, args.join(", ")))
        }

        ExprKind::Range(r) => {
            let start = r.start.as_ref().map(|s| render_expr(s, e)).transpose()?;
            let end = r.end.as_ref().map(|s| render_expr(s, e)).transpose()?;
            Ok(match (start, end) {
                (Some(s), Some(en)) => format!("{}..{}", s, en),
                (Some(s), None) => format!("{}..", s),
                (None, Some(en)) => format!("..{}", en),
                (None, None) => "..".to_string(),
            })
        }

        ExprKind::FormatString(fs) => {
            let parts = fs.parts.iter().map(|p| match p {
                FormatTemplatePart::Literal(lit) => Ok(lit.clone()),
                FormatTemplatePart::Placeholder(_ph) => {
                    let rendered = "arg".to_string();
                    Ok(format!("${{{}}}", rendered))
                }
            }).collect::<Result<Vec<_>>>()?;
            Ok(format!("\"{}\"", parts.join("")))
        }

        ExprKind::Break(_) => Ok("break".to_string()),
        ExprKind::Continue(_) => Ok("continue".to_string()),
        _ => Ok("/* TODO */".to_string()),
    }
}

fn render_expr_single(body: &BExpr, e: &mut KotlinEmitter) -> Result<String> {
    if let ExprKind::Block(block) = body.kind() {
        let mut parts = Vec::new();
        for stmt in &block.stmts {
            if let BlockStmt::Expr(se) = stmt { parts.push(render_expr(&se.expr, e)?); }
        }
        Ok(parts.join(" "))
    } else { render_expr(body, e) }
}

fn render_invoke_target(target: &ExprInvokeTarget, e: &mut KotlinEmitter) -> Result<String> {
    match target {
        ExprInvokeTarget::Function(name) => Ok(name.to_string().replace("::", ".")),
        ExprInvokeTarget::Method(sel) => Ok(format!("{}.{}", render_expr(&sel.obj, e)?, sel.field.name)),
        ExprInvokeTarget::Expr(bexpr) => render_expr(bexpr, e),
        _ => Ok("call".to_string()),
    }
}

fn render_match_pat(pat: &Option<fp_core::ast::BPattern>) -> String {
    match pat {
        Some(p) => match &p.kind {
            PatternKind::Ident(id) => id.ident.name.clone(),
            PatternKind::Wildcard(_) => "else".to_string(),
            _ => "else".to_string(),
        },
        None => "else".to_string(),
    }
}

// ── Value ────────────────────────────────────────────────────────────────────

fn render_value(val: &Value) -> String {
    match val {
        Value::Bool(v) => v.value.to_string(),
        Value::Int(v) => v.value.to_string(),
        Value::UInt(v) => v.value.to_string(),
        Value::BigInt(v) => v.value.to_string(),
        Value::Decimal(v) => v.value.to_string(),
        Value::BigDecimal(v) => v.value.to_string(),
        Value::Char(v) => format!("'{}'", v.value),
        Value::String(v) => format!("\"{}\"", v.value.escape_default()),
        Value::Unit(_) | Value::Null(_) | Value::None(_) => "null".to_string(),
        Value::Some(v) => render_value(&v.value),
        Value::Option(v) => v.value.as_ref().map(|i| render_value(i)).unwrap_or_else(|| "null".to_string()),
        Value::List(l) => {
            let items: Vec<String> = l.values.iter().map(|v| render_value(v)).collect();
            format!("listOf({})", items.join(", "))
        }
        Value::Map(m) => {
            let entries: Vec<String> = m.entries.iter()
                .map(|e| format!("{} to {}", render_value(&e.key), render_value(&e.value)))
                .collect();
            format!("mapOf({})", entries.join(", "))
        }
        Value::Tuple(t) => {
            let items: Vec<String> = t.values.iter().map(|v| render_value(v)).collect();
            format!("Pair({})", items.join(", "))
        }
        _ => "null".to_string(),
    }
}

// ── Operators ────────────────────────────────────────────────────────────────

fn kotlin_bin_op(kind: &BinOpKind) -> &str {
    match kind {
        BinOpKind::Add => "+", BinOpKind::Sub => "-", BinOpKind::Mul => "*", BinOpKind::Div => "/",
        BinOpKind::Mod => "%", BinOpKind::And | BinOpKind::BitAnd => "&&",
        BinOpKind::Or | BinOpKind::BitOr => "||", BinOpKind::Eq => "==", BinOpKind::Ne => "!=",
        BinOpKind::Lt => "<", BinOpKind::Gt => ">", BinOpKind::Le => "<=", BinOpKind::Ge => ">=",
        BinOpKind::Shl => "shl", BinOpKind::Shr => "shr", BinOpKind::BitXor => "xor",
        _ => "?",
    }
}

fn kotlin_un_op(kind: &UnOpKind) -> &str {
    match kind { UnOpKind::Not => "!", UnOpKind::Neg => "-", UnOpKind::Deref => "*", _ => "?" }
}

fn intrinsic_name(kind: &fp_core::intrinsics::calls::CallKind) -> String {
    use fp_core::intrinsics::calls::OpKind;
    use fp_core::intrinsics::calls::IntrinsicKind;
    match kind {
        fp_core::intrinsics::calls::CallKind::Op(op) => match op {
            OpKind::Print => "print".into(),
            OpKind::Println => "println".into(),
            OpKind::Format => "String.format".into(),
            _ => format!("op_{:?}", op).to_lowercase(),
        },
        fp_core::intrinsics::calls::CallKind::Intrinsic(i) => match i {
            IntrinsicKind::Len => "count()".into(),
            IntrinsicKind::Panic => "error".into(),
            _ => format!("intr_{:?}", i).to_lowercase(),
        },
    }
}

// ── Type mapping ─────────────────────────────────────────────────────────────

fn kotlin_type_from_ty(ty: &Ty, _e: &KotlinEmitter) -> String {
    match ty {
        Ty::Primitive(prim) => match prim {
            TypePrimitive::Bool => "Boolean".into(),
            TypePrimitive::Char => "Char".into(),
            TypePrimitive::String => "String".into(),
            TypePrimitive::Int(int_ty) => match int_ty {
                TypeInt::I8 => "Byte".into(), TypeInt::I16 => "Short".into(),
                TypeInt::I32 => "Int".into(), TypeInt::I64 => "Long".into(),
                TypeInt::U8 => "UByte".into(), TypeInt::U16 => "UShort".into(),
                TypeInt::U32 => "UInt".into(), TypeInt::U64 => "ULong".into(),
                _ => "Int".into(),
            },
            TypePrimitive::Decimal(d) => match d {
                fp_core::ast::DecimalType::F32 => "Float".into(),
                fp_core::ast::DecimalType::F64 => "Double".into(),
                _ => "Double".into(),
            },
            TypePrimitive::List => "List<Any>".into(),
        },
        Ty::Vec(v) => format!("List<{}>", kotlin_type_from_ty(&v.ty, _e)),
        Ty::Struct(s) => s.name.name.clone(),
        Ty::Enum(en) => en.name.name.clone(),
        Ty::Reference(r) => kotlin_type_from_ty(&r.ty, _e),
        Ty::Expr(expr) => map_name_to_kt(&expr_to_name(expr)),
        Ty::Unit(_) => "Unit".into(),
        Ty::Slice(sl) => format!("List<{}>", kotlin_type_from_ty(&sl.elem, _e)),
        Ty::Any(_) | Ty::Unknown(_) => "Any".into(),
        Ty::Nothing(_) => "Nothing".into(),
        _ => "Any".into(),
    }
}

fn expr_to_name(expr: &Expr) -> String {
    match expr.kind() {
        ExprKind::Name(name) => name_to_string(name),
        ExprKind::Select(sel) => {
            format!("{}.{}", expr_to_name(&sel.obj), sel.field.name.as_str())
        }
        _ => format!("Any"),
    }
}

fn name_to_string(name: &fp_core::ast::Name) -> String {
    use fp_core::ast::Name::*;
    match name {
        Ident(id) => id.name.clone(),
        Path(p) => p.segments.iter().map(|s| s.name.as_str()).collect::<Vec<_>>().join("."),
        ParameterPath(pp) => {
            let base = pp.segments.iter()
                .map(|s| {
                    let name = s.ident.name.as_str();
                    if s.args.is_empty() { name.to_string() }
                    else {
                        let args = s.args.iter()
                            .map(|ty| kotlin_type_from_ty(ty, &KotlinEmitter::new()))
                            .collect::<Vec<_>>().join(", ");
                        format!("{}<{}>", name, args)
                    }
                })
                .collect::<Vec<_>>().join(".");
            base
        },
    }
}

fn map_name_to_kt(name: &str) -> String {
    if let Some(inner) = name.strip_prefix("Vec<").and_then(|s| s.strip_suffix(">")) {
        return format!("MutableList<{}>", map_name_to_kt(inner));
    }
    if let Some(inner) = name.strip_prefix("Option<").and_then(|s| s.strip_suffix(">")) {
        return format!("{}?", map_name_to_kt(inner));
    }
    match name {
        "str" | "String" => "String".into(),
        "char" => "Char".into(),
        "bool" => "Boolean".into(),
        "i8" => "Byte".into(), "i16" => "Short".into(),
        "i32" => "Int".into(), "i64" => "Long".into(),
        "u8" => "UByte".into(), "u16" => "UShort".into(),
        "u32" => "UInt".into(), "u64" => "ULong".into(),
        "f32" => "Float".into(), "f64" => "Double".into(),
        "usize" => "Long".into(), "isize" => "Long".into(),
        _ => name.to_string(),
    }
}
