# Magnet.toml for shared library project
# This file is used by the magnet CLI tool to manage workspace dependencies

[project]
name = "shared-lib"
version = "0.1.0"
description = "Shared libraries used across projects"
authors = ["Example User <user@example.com>"]

[workspace]
members = ["crates/*"]
exclude = []
resolver = "2"

# Define workspace dependencies that are shared across crates
[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
uuid = { version = "1.3", features = ["v4"] }