[package]
name = "fp"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]

[dev-dependencies]
criterion = "0.8"
fp-core = { path = "crates/fp-core" }
fp-resolve = { path = "crates/fp-resolve" }
fp-rust = { path = "crates/fp-rust" }
fp-typing = { path = "crates/fp-typing" }
fp-compiler = { path = "crates/fp-compiler" }
fp-backend = { path = "crates/fp-backend" }

[[bench]]
name = "eight_queens"
harness = false


[workspace]
resolver = "2"
members = [
    "crates/*",
]
exclude = [
    "crates/fp-shell-core",
]
default-members = ["crates/fp-cli"]
