# Magnet.toml for Project 1
# This file is used by the magnet CLI tool to manage workspace dependencies

[project]
name = "project1"
version = "0.1.0"
description = "Project 1 with magnet super-workspace"
authors = ["Example User <user@example.com>"]

[workspace]
members = ["crates/*"]
exclude = []
resolver = "2"

# Auto-detect shared crates across projects
# This will automatically find and use path dependencies
[dependencies]
shared-types = { auto = true }
shared-utils = { auto = true }
anyhow = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"