[package]
name = "shared-types"
version = "0.1.0"
edition = "2024"
description = ""
authors = []

[dependencies.uuid]
version = "1.3"
features = ["v4"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
