# Magnet.toml for Project 2
# This file is used by the magnet CLI tool to manage workspace dependencies

[project]
name = "project2"
version = "0.1.0"
description = "Project 2 with magnet super-workspace"
authors = ["Example User <user@example.com>"]

[workspace]
members = ["crates/*"]
exclude = []
resolver = "2"

